version: 3.2.47

services:
  backend:
    env_file:
      - .env
    container_name: Django
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/backend/:/backend
      - staticfiles:/backend/staticfiles
    command: >
      sh -c 
      "python manage.py collectstatic --no-input && 
      python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py create_superuser &&
      gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"
    depends_on:
      - database
      - redis

  database:
    env_file:
      - .env
    container_name: Postgresql
    image: postgres:14-alpine3.17

  redis:
    container_name: Redis
    image: redis:7.0.5-alpine3.17

  nginx:
    container_name: Nginx
    build:
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/etc/nginx/logs
      - staticfiles:/backend/staticfiles/
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  staticfiles:
