INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cachalot",
    "drf_yasg",
    "management",
    "employee",
    "customer",
    "request",
    "development",
    'rest_framework_simplejwt',
]
