# Generated by Django 4.1.7 on 2023-09-10 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_user'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_change', models.DateTimeField()),
                ('employees', models.ManyToManyField(related_name='developments', to='employee.employee')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='request.request')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='request.state')),
            ],
        ),
    ]
