# Generated by Django 4.1.7 on 2023-09-10 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
