# Generated by Django 4.1.7 on 2023-09-10 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('employee', '0004_alter_employee_user'),
        ('development', '0002_alter_development_last_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='development.development')),
                ('employees', models.ManyToManyField(related_name='documentations', to='employee.employee')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='request.state')),
            ],
        ),
    ]
